### ISSUE TITLE
Zdharma has been deleted from Github 

### ISSUE THREAD

**Issue by luong-komorebi** [kornicameister/dotfiles#1855]
More context over here https://github.com/zdharma-continuum/I_WANT_TO_HELP 

Could you check your local machine for possible copy of zsh-unique-id? This repo has 0 fork so it is really hard to find a copy of it and repost on @zdharma-continuum

**Comment by kornicameister** [comment]
That is really disturbing. I need to take a look at this sometime soon but I feel like fish is coming.

**Comment by luong-komorebi** [comment]
zdharma-continuum has gained the repo for now. Thank you for your help :D you should also update your configurations to point to this repo
